### ISSUE TITLE
Unauthorized access after first login

### ISSUE THREAD

**Issue by handycz** [zipekjan/minicloud-client-java-lib#1]
After building the key with different password than the current password is, I'm getting 

> Failed to save your settings. Unauthorized access.

error. 
When new key is built with same password as the current one, everything works fine.

**Comment by SkaceKamen** [comment]
This is issue with client, not library

**Comment by SkaceKamen** [comment]
Moved https://github.com/zipekjan/minicloud-client-java/issues/2
